name: CI Build and SonarCloud Scan

on:
  push:
    branches:
      - main
      - develop

  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build-and-scan:
    runs-on: ubuntu-latest
    env:
      INFISICAL_TOKEN: ${{ secrets.INFISICAL_TOKEN }}
      GITHUB_TOKEN:    ${{ secrets.GITHUB_TOKEN }}
      SONAR_TOKEN:     ${{ secrets.SONAR_TOKEN }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install pnpm & Infisical CLI
        run: |
          npm install -g pnpm
          npm install -g @infisical/cli

      - name: Install dependencies (sin scripts)
        run: infisical run -- pnpm install --ignore-scripts

      - name: Generate Prisma clients (con infisical)
        run: infisical run -- pnpm db:generate:all

      - name: Run tests & coverage (con infisical)
        run: infisical run -- pnpm test:cov

      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@v5.2.0
        with:
          args: >
            -Dsonar.organization=${{ secrets.SONAR_ORGANIZATION }}
            -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }}
            -Dsonar.sources=backend,frontend
            -Dsonar.exclusions=**/node_modules/**,**/.next/**,**/dist/**,**/coverage/**,**/*.spec.ts
            -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN:  ${{ secrets.SONAR_TOKEN }}
